services:
  postgres:
    container_name: shopper-postgres
    image: postgres:16.0-alpine3.18
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopper-db